### ISSUE TITLE
Progressive Web Apps

### ISSUE THREAD

**Issue by pbiswas101** [the-ethan-hunt/first-timers-guide#191]
@the-ethan-hunt I would like to work on this.

Also specify the folder as where should I put it?

**Comment by RN0311** [comment]
Hey, @pbiswas101 it will be great if you start writing on this topic! We'll decide once @the-ethan-hunt will be back, I guess he must be busy with other things.
Just a random tip:- Even if GSSoC ends, don't hesitate to submit your PR(s) since it will further enhance your learning curve!

Good luck! :smiley:

**Comment by the-ethan-hunt** [comment]
Assigned to @pbiswas101 
Currently add it to web containers. We will decide that later.

**Comment by pbiswas101** [comment]
Okay
